/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary':                    '#003b1b',
        'on-primary':                 '#ffffff',
        'primary-container':          '#14532d',
        'on-primary-container':       '#87c695',
        'primary-fixed':              '#b1f2be',
        'primary-fixed-dim':          '#96d5a3',
        'on-primary-fixed':           '#00210d',
        'on-primary-fixed-variant':   '#12512c',
        'secondary':                  '#006e2d',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#7cf994',
        'on-secondary-container':     '#007230',
        'secondary-fixed':            '#7ffc97',
        'secondary-fixed-dim':        '#62df7d',
        'on-secondary-fixed':         '#002109',
        'on-secondary-fixed-variant': '#005320',
        'tertiary':                   '#4f2700',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#703a00',
        'on-tertiary-container':      '#ffa14e',
        'tertiary-fixed':             '#ffdcc3',
        'tertiary-fixed-dim':         '#ffb77d',
        'on-tertiary-fixed':          '#2f1500',
        'on-tertiary-fixed-variant':  '#6e3900',
        'surface':                    '#faf8ff',
        'surface-dim':                '#d2d9f4',
        'surface-bright':             '#faf8ff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f2f3ff',
        'surface-container':          '#eaedff',
        'surface-container-high':     '#e2e7ff',
        'surface-container-highest':  '#dae2fd',
        'surface-variant':            '#dae2fd',
        'surface-tint':               '#2e6a41',
        'on-surface':                 '#131b2e',
        'on-surface-variant':         '#404941',
        'outline':                    '#717970',
        'outline-variant':            '#c0c9be',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'inverse-surface':            '#283044',
        'inverse-on-surface':         '#eef0ff',
        'inverse-primary':            '#96d5a3',
        'background':                 '#faf8ff',
        'on-background':              '#131b2e',
        kisan: {
          50: '#f2f9f1', 100: '#e1f3df', 200: '#c3e7be',
          300: '#97d490', 400: '#64ba5c', 500: '#3f9e36',
          600: '#2f7e27', 700: '#276422', 800: '#234f1f',
          900: '#1e421c', 950: '#0c240b'
        }
      },
      fontFamily: {
        'jakarta': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      spacing: {
        'gutter-mobile': '1rem',
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.25rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '2.5rem',
        'space-4xl': '3rem',
      }
    },
  },
  plugins: [],
}
