export const BOOKING_STATUS = {
  BOOKED: 'BOOKED',
  CONFIRMED: 'CONFIRMED',
  CHECKED_IN: 'CHECKED_IN',
  ELIGIBLE_FOR_RELEASE: 'ELIGIBLE_FOR_RELEASE',
  RELEASED: 'RELEASED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
};

export const MANDI_STATUS = {
  GREEN: 'Green',
  AMBER: 'Amber',
  RED: 'Red',
};

export const QUANTITY_BANDS = {
  BAND_0_5: '0-5q',
  BAND_5_15: '5-15q',
  BAND_15_PLUS: '15q+',
};
